In [3]:
import numpy as np

In [4]:
my_list=[1,2,3,4,5,6]
array= np.array(my_list,dtype=int)
print(array)

[1 2 3 4 5 6]


In [5]:
print(type(array))

<type 'numpy.ndarray'>


In [6]:
print(len(array))

6


In [7]:
print(array.ndim)

1


In [8]:
print(array.shape)

(6L,)


In [9]:
array2=array.reshape(3,2)
print(array2)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
array2.shape

(3L, 2L)

In [16]:
array3=array.reshape(3,-1)
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
print(array3.shape)

(3L, 2L)


In [18]:
my_list2=[1,2,3,4,5]
my_list3=[2,3,4,5,6]
my_list4=[1,5,9,7,4]
mul=np.array([my_list2,my_list3,my_list4])

In [19]:
print(mul)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [1 5 9 7 4]]


In [20]:
print(mul.shape)

(3L, 5L)


In [21]:
mul.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 1, 5, 9, 7, 4]])

In [22]:
a=range(17)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


In [23]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2,1)
print(b)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [24]:
x=np.array([[1,2],[3,4]],dtype=float)

In [25]:
y=np.array([[6,5],[8,9]],dtype=float)

In [26]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[6. 5.]
 [8. 9.]]


In [27]:
print(x+y)

[[ 7.  7.]
 [11. 13.]]


In [28]:
print(np.add(x,y))

[[ 7.  7.]
 [11. 13.]]


In [29]:
print(np.multiply(x,y))

[[ 6. 10.]
 [24. 36.]]


In [30]:
print(np.dot(x,y))

[[22. 23.]
 [50. 51.]]


In [31]:
print(np.divide(x,y))

[[0.16666667 0.4       ]
 [0.375      0.44444444]]


In [32]:
print(np.sum(x))

10.0


In [33]:
print(np.sum(x,axis=0))

[4. 6.]


In [34]:
print(np.sum(x,axis=1))

[3. 7.]


indexing

In [35]:
arr1=np.array([my_list2,my_list3,my_list4])

In [36]:
print(arr1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [1 5 9 7 4]]


In [37]:
arr1[1:,:2]

array([[2, 3],
       [1, 5]])

In [45]:
arr1[1:,3:]

array([[5, 6],
       [7, 4]])

In [47]:
print(my_list)

[1, 2, 3, 4, 5, 6]


In [56]:
##val=2

arr1[arr1<3]

array([1, 2, 2, 1])

In [59]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [62]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [64]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [66]:
np.random.rand(3,3)

array([[0.89492336, 0.22748653, 0.37901693],
       [0.13262635, 0.61610072, 0.61484895],
       [0.40302155, 0.91199599, 0.06617542]])